config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/home', to: 'pages#home'
  #get 'recipes', to: 'recipes#index'
  #get 'recipes/new', to: 'recipes#new', as: 'new_recipe'
  #get 'recipes/:id', to: 'recipes#show'
  
  resources :recipes do
    resources :comments, only: [:create, :destroy]
    member do
      post 'like'
    end
  end
  
  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]
  resources :ingredients, except: [:destroy]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  get 'pages/top', to: 'pages#top'
  get 'pages/middle', to: 'pages#middle'
  get 'pages/bottom', to: 'pages#bottom'
  
  mount ActionCable.server => '/cable'
  get '/chat', to: 'chatrooms#show'
  
  resources :messages, only: [:create]
  
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true, length: {minimum: 5, maximum: 500 }
  validates :chef_id, presence: true # added as per test recipe_test.rb line10
  mount_uploader :picture, PictureUploader
  belongs_to :chef # use chef as the singular as 1 X Chef per recipe
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  default_scope -> { order(updated_at: :desc) }  #this arranges the order of the recipess from most recent down
  
  # Validates the size of an uploaded picture
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "Should be less than 5MB!")
    end
  end
  
  def thumbs_up_total
    self.likes.where(like: true).size
  end

  def thumbs_down_total
    self.likes.where(like: false).size    
  end
  
  
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy, :like]
  before_action :require_user, except: [:index, :show, :like]
  before_action :require_user_like, only: [:like]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  
  def index
    @recipes = Recipe.paginate(page: params[:page], per_page: 5) #This will paginate the page
    #@recipes = Recipe.all
  end
  
  def show
    @comment = Comment.new
    @comments = @recipe.comments.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @recipe = Recipe.new
  end
  
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef = current_chef
    if @recipe.save
      #session[:chef_id] = chef.id 
      flash[:success] = "Recipe was created sucessfully"
      redirect_to recipe_path(@recipe)
    else
      flash.now[:danger] = "Oops!! Something didn't go quite right here... Lets try that again!"
      render "new"
    end
  end
  
  def edit
     
  end
  
  def update
    if @recipe.update(recipe_params)
      flash[:success] = "Update was sucessfull"
      redirect_to recipe_path(@recipe)
    else
      flash.now[:danger] = "Oops!! Something didn't go quite right here... Lets try that again!"
      render 'edit'
    end
  end
  
  def destroy
    @recipe.destroy
    flash[:success] = "Recipe has been deleted"
    redirect_to recipes_path
  end
  
  def like
    like = Like.create(like: params[:like], chef: current_chef, recipe: @recipe)
    if like.valid?
      flash[:success] = "You have 'liked' it"
      redirect_to :back
    else
      flash[:danger] = "You can only like/dislike a recipe once"
      redirect_to :back
    end
  end
  
  private
  
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end
  
    def recipe_params
      #params.require(:recipe).permit(:name, :description) See action below if you want to select ingredients in form as well..
      params.require(:recipe).permit(:name, :description, :picture, ingredient_ids: [])
    end
    
    def require_user_like
      if !logged_in?
        flash[:danger] = "You must be logged in to perform that action"
        redirect_to :back
      end
    end
    
    def require_same_user 
      if current_chef != @recipe.chef and !current_chef.admin?
        flash[:danger] = "You can only edit or delete your own recipes"
        redirect_to recipes_path
      end
    end
    
  
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= render 'shared/error', obj: @recipe %>

  <div class="row">
   <div class="col-md-12">
    <%= form_for(@recipe, :html => {class: "form-horizontal", role: "form"}) do |f| %> <!-- This is how you add bootstrap class in ruby code -->
     <div class="form-group">
       <div class="control-label col-md-2">
         <%= f.label :name %>
       </div>
     <div class="col-md-8">
        <%= f.text_field :name, class: "form-control", placeholder: "Name of recipe", autofocus: true %>
      </div>
     </div>
     
     <div class="form-group">
       <div class="control-label col-md-2">
         <%= f.label :description %>
       </div>
     <div class="col-md-8">
        <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Enter recipe details here.." %>
      </div>
     </div>
     
     <div class="form-group">
       <div class="control-label col-md-2">
         <%= f.label :picture %>
       </div>
     <div class="col-md-8">
        <%= f.file_field  :picture, class: "form-control", placeholder: "Upload picture here.." %>
      </div>
     </div>
     
      <div class="form-group">
        <div class="row">
         <div class="col-md-offset-2 col-md-8">
           <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |cbox| %>
             <%  cbox.label(class: "checkbox-inline input_checkbox") {cbox.check_box(class: "checkbox") + cbox.text } %>
           <% end %>
         </div>
       </div>
     </div>
     
     <div class="form-group">
       <div class="col-md-offset-2 col-md-10 ">
         <%= f.submit class: "btn btn-primary btn-lg nice_green" %>
         <!--<%= link_to "All Recipes", recipes_path, class: "btn btn-primary btn-lg nice_green" %> -->
       </div>
     </div>
    <% end %>
    <div class="col-md-4 col-md-offset-4">
      <%= link_to "Cancel reguest and return to recipes listing", recipes_path, class: "btn btn-sm btn-primary nice_green" %>
    </div>
   </div>
  </div>
  
 <script type="text/javascript">
   $('#recipe_picture').bind('change', function() {
     var size_in_megabytes = this.files[0].size/1024/1024;
     if (size_in_megabytes > 5) {
       alert('Maximum file size is 5MB. Please choose a smaller file.');
     }
   });
 </script>

app/views/recipes/_recipe.html.erb
<% obj.each do |recipe| %>
  <div class="row">
    <div class= "col-md-2">
      <section class= "chef_info center">
        <%= gravatar_for(recipe.chef, size: 120) %> <!-- use the |recipe| to access the chef details for a=vatar here -->
      </section>
    </div>
    <div class= "col-md-8 well <%= cycle('profile-green', '') %>">
      <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
        <p><%= truncate(recipe.description, length: 150) %></p>
        <% if recipe.ingredients.any? %> <!-- The code below will enable all the ingredients to be displayed in Ingredients/show -->
          <p>Ingredients: <%= render recipe.ingredients %></p> <!-- Need to add an Ingredient partial -->
        <% end %> 
          <p><span class="quiet"><small>Created <%= time_ago_in_words(recipe.created_at) %> ago by <%= recipe.chef.chefname.capitalize  %> | <%= pluralize(recipe.comments.count, "Comment") %></small></span>
        </p>
          <% if logged_in? && (current_chef == recipe.chef || current_chef.admin?) %>
            <%= link_to "Edit This Recipe", edit_recipe_path(recipe), class: "btn btn-sm btn-warning nice_green white_font"%>
            <%= link_to "Delete This Recipe", recipe_path(recipe), method: :delete, 
                                                             data: {confirm: "Are you sure??"},  
                                                             class: "btn btn-sm btn-danger white_font"%>
        <% end %>
      <div class="row">
        <div class="pull-right liking">
          <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
            <i class="glyphicon glyphicon-thumbs-up"></i> 
          <% end %> <%= recipe.thumbs_up_total %> || 
          <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
            <i class="glyphicon glyphicon-thumbs-down"></i>
          <% end %> <%= recipe.thumbs_down_total %>
        </div>
      </div>
    </div>
  </div>  
<% end %>

app/views/recipes/edit.html.erb
<%= render "shared/page_title", title: "edit this recipe" %>



<%= render "recipes/form" %>

app/views/recipes/index.html.erb
<%= render "shared/page_title", title: "All recipes" %>

<div align="center">
  <%= will_paginate %>
</div>
<%= render "recipes/recipe", obj: @recipes %>
<div align="center">
  <%= will_paginate %>
</div>

app/views/recipes/new.html.erb
<%= render "shared/error", obj: @recipe %>  <!-- obj: @recipe this passes in this instance variable into the partial. If you want to run this in chefs - obj: @chef  -->




<%= render "recipes/form" %>

app/views/recipes/show.html.erb
<%= render "shared/page_title", title: @recipe.name %>

<div class= "well col-md-8 col-md-offset-2">
  <h4 class= "description center"><strong>Description: </strong></h4>
  <hr />
    <%= simple_format(@recipe.description) %>
  <br />
    <div class="yummy">
      <%= image_tag @recipe.picture.url if @recipe.picture? %>
    </div>
  <% if @recipe.ingredients.any? %>
    <p><strong>Ingredients:</strong> <%= render @recipe.ingredients %></p>
  <% end %>
  <div class="pull-right">
      <p class="center">
       <em> Created by:</em>
      </p>
      <p class="center">
        <%= link_to gravatar_for(@recipe.chef), chef_path(@recipe.chef) %>
      </p>
      <p class ="center">
        <small><%= @recipe.chef.chefname.capitalize %></small>
        <div class="pull-right"><%= time_ago_in_words(@recipe.created_at) %> ago</div>
      </p>
  </div>
  <div class="recipe-actions">
    <% if logged_in? && (current_chef == @recipe.chef || current_chef.admin?) %>
        <%= link_to "Edit This Recipe", edit_recipe_path(@recipe), class: "btn btn-sm btn-warning nice_green"%>
        <%= link_to "Delete This Recipe", recipe_path(@recipe), method: :delete, 
                                                             data: {confirm: "Are you sure??"},  
                                                             class: "btn btn-sm btn-danger"%>
    <% end %>
    <%= link_to "All Recipes", recipes_path, class: "btn btn-sm btn-warning nice_green"%>
   </div>
  </div>
  
  <div class="row liking">
    <div class="row col-md-8 col-md-offset-2">
      <%= link_to like_recipe_path(@recipe, like: true), method: :post do %>
        <i class="glyphicon glyphicon-thumbs-up"></i> 
      <% end %> <%= @recipe.thumbs_up_total %>||
      <%= link_to like_recipe_path(@recipe, like: false), method: :post do %>
        <i class="glyphicon glyphicon-thumbs-down"></i> 
      <% end %><%= @recipe.thumbs_down_total %>
    </div>
  </div>

<% if logged_in? %>
  <%= render 'comments/newcomment' %>
<% end %>

<% if @recipe.comments.count > 0 %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h4>Comments: <%= @recipe.comments.count %></h4>
        <div id="messages">
          <%= render partial: 'comments/comments', object: @comments %>
        </div>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h4>No Comments Yet..</h4>
    </div>
  </div>
<% end %>