config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/home', to: 'pages#home'
  #get 'recipes', to: 'recipes#index'
  #get 'recipes/new', to: 'recipes#new', as: 'new_recipe'
  #get 'recipes/:id', to: 'recipes#show'
  
  resources :recipes do
    resources :comments, only: [:create, :destroy]
    member do
      post 'like'
    end
  end
  
  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]
  resources :ingredients, except: [:destroy]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  get 'pages/top', to: 'pages#top'
  get 'pages/middle', to: 'pages#middle'
  get 'pages/bottom', to: 'pages#bottom'
  
  mount ActionCable.server => '/cable'
  get '/chat', to: 'chatrooms#show'
  
  resources :messages, only: [:create]
  
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  before_save { self.name = name.downcase }
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
  
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
   before_action :set_ingredient, only: [:show, :edit, :update]
  
  def new
    @ingredient = Ingredient.new
  end
  
  def create
    @ingredient = Ingredient.new(ingredient_params)
    if  @ingredient.save
     flash[:success] = "Ingredient has been added.."
     redirect_to ingredient_path(@ingredient)
   else
     flash.now[:danger] = "Oops! Give that another try.."
     render "new"
    end
  end
  
  def edit
    
  end
  
  def update
    if @ingredient.update(ingredient_params)
      flash[:success] = "Ingredient was sucessfully updated"
      redirect_to ingredient_path(@ingredient)
    else
      flash.now[:danger] = "Something went Wrong! Try it again.."
      render "edit"
    end
  end
  
  def show
    @ingredient_recipes = @ingredient.recipes.paginate(page: params[:page], per_page: 5)
  end
  
  def index
    @ingredients = Ingredient.paginate(page: params[:page], per_page: 5)
  end
  
  private
  
  def ingredient_params
    params.require(:ingredient).permit(:name)
  end
  
  def set_ingredient
    @ingredient = Ingredient.find(params[:id])
  end
  
end

app/views/ingredients/_form.html.erb
<div class="row">
   <div class="col-md-12">
    <%= form_for(@ingredient, :html => {class: "form-horizontal", role: "form"}) do |f| %> <!-- This is how you add bootstrap class in ruby code -->
     <div class="form-group">
       <div class="control-label col-md-2">
         <%= f.label :name %>
       </div>
     <div class="col-md-8">
        <%= f.text_field :name, class: "form-control", placeholder: "Enter ingredient", autofocus: true %>
      </div>
     </div>
     
    
     <div class="form-group">
       <div class="col-md-offset-2 col-md-10 ">
         <%= f.submit class: "btn btn-primary nice_green_inverse" %>
          <%= link_to "All Ingredients", ingredients_path, class: "btn btn-primary btn-sm nice_green" %> 
         <%= link_to "All Recipes", recipes_path, class: "btn btn-primary btn-sm nice_green" %> 
       </div>
     </div>
    <% end %>
    <div class="col-md-4 col-md-offset-4">
      <%= link_to "Cancel reguest and return to Ingredients listing", ingredients_path, class: "btn btn-sm btn-primary nice_green" %>
    </div>
   </div>
  </div>

app/views/ingredients/_ingredient.html.erb
<span><%= link_to ingredient.name.capitalize, ingredient_path(ingredient) %> &nbsp; </span> <!-- &nbsp = non breaking space -->

app/views/ingredients/edit.html.erb
<%= render "shared/page_title", title: "Change this ingredient '#{ @ingredient.name}' "  %>
<%= render 'shared/error', obj: @ingredient %>

<%= render 'form' %>

app/views/ingredients/index.html.erb
<%= render "shared/page_title", title: "Ingredients".capitalize %>

<div align="center">
  <%= will_paginate %>
</div>
<div align="center">
  <% @ingredients.each do |ing| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-sm-6 col-sm-offset-3 <%= cycle('profile-green', '') %>">
          <li class="chef-title"><%= link_to ing.name.capitalize, ingredient_path(ing) %></li>
          <li><small>Added to <%= pluralize(ing.recipes.count, "recipe")if ing.recipes  %></small></li>
          <% if logged_in? && current_chef.admin? && %>
            <li><%= link_to "Edit This Ingredient", edit_ingredient_path(ing) %></li>
          <% end %>
        </div>
      </div>  
    </ul>
  <% end %>
</div>
<div align="center">
  <%= will_paginate %>
</div>

app/views/ingredients/new.html.erb
<%= render "shared/page_title", title: "Add a new ingredient" %>
<%= render 'shared/error', obj: @ingredient %>

<%= render 'form' %>

app/views/ingredients/show.html.erb
<%= render 'shared/page_title', title: "#{@ingredient.name.capitalize}" %>

<% if @ingredient.recipes.count != 0 %>
  <h4 align="center">Recipes containing <%= @ingredient.name %></h4>
  <div align="center">
    <%= will_paginate @ingredient_recipes %>
  </div>
    <%= render "recipes/recipe", obj: @ingredient_recipes %>
    <div align="center">
    <%= will_paginate @ingredient_recipes %>
  </div>
<% else %>
  <h4 align="center">There are no recipes containing <span class="hither-green"><%= @ingredient.name %></span> yet</h4>

<% end %>