config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/home', to: 'pages#home'
  #get 'recipes', to: 'recipes#index'
  #get 'recipes/new', to: 'recipes#new', as: 'new_recipe'
  #get 'recipes/:id', to: 'recipes#show'
  
  resources :recipes do
    resources :comments, only: [:create, :destroy]
    member do
      post 'like'
    end
  end
  
  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]
  resources :ingredients, except: [:destroy]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  get 'pages/top', to: 'pages#top'
  get 'pages/middle', to: 'pages#middle'
  get 'pages/bottom', to: 'pages#bottom'
  
  mount ActionCable.server => '/cable'
  get '/chat', to: 'chatrooms#show'
  
  resources :messages, only: [:create]
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  
  <small>
    <strong>Created by: <a href="http://www.vincethewalker.com/">Vincent Walker</a></strong>
   </small>
     
    <nav>
      <ul>
        <li><%= link_to "About", "#" %></li>
      </ul>
    </nav>
   
 </footer>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= msg %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand" href="#">Brand</a> --> <!-- Deleted this link and replaced by the ruby one below -->
      <%= link_to "MyRecipies", root_path, class:"navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
          <li><%= link_to "Chefs", chefs_path %></li>
          <li><%= link_to "All Recipes", recipes_path  %></li>
          <li><%= link_to "Ingredients", ingredients_path %></li>
        <% if logged_in? %>
          <li><%= link_to "ChefChat", chat_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Options <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Create New Recipe", new_recipe_path  %></li>
              <% if current_chef.admin? %>
                <li><%= link_to "Add a New Ingredient", new_ingredient_path %></li>
              <% end %>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Avaliable Ingredients:" %></li>
              <% Ingredient.all.each do |ingredient| %>
                 <li><%= link_to ingredient.name.capitalize, ingredient_path(ingredient) %></li>
              <% end %>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        <% end %>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if current_chef %>
          <li><%= link_to "Log out", logout_path, method: :delete, class: "btn btn-danger nice_green_nav" %></li>
        <% else %>
          <li><%= link_to "Log in", login_path, class: "btn btn-danger nice_green_nav" %></li>
        <% end %>
        <!--<li><a href="#">Link</a></li>-->
      <% if current_chef %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_chef.chefname %>'s profile <%= "(Admin)" if current_chef.admin? %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "View your Profile", chef_path(current_chef) %></li>
              <li><%= link_to "Edit your Profile", edit_chef_path(current_chef) %></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", logout_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myrecipes</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navigation.html.erb" %>
    
    <%= render "layouts/messages.html.erb" %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render "layouts/footer.html.erb" %>
  </body>
</html>